"""
Financial Bonsai — Backtester
Reads historical OHLC data and simulates the MA7/MA21 crossover strategy.
Answers the question: would this strategy have made money?

Usage: python3 backtest.py
Requires: history_BTC_60m.csv, history_ETH_60m.csv, history_SOL_60m.csv
(generated by download_history.py)
"""

import csv

# Kraken taker fee: 0.40% per trade (lowest volume tier, $0-$10k)
# This applies to EACH trade — both the buy and the sell
FEE_PCT = 0.40


def load_prices(filename):
    """Read a history CSV and return a list of [datetime, close_price] pairs."""
    prices = []
    with open(filename, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            prices.append([row["datetime"], float(row["close"])])
    return prices


def calculate_ma(prices, position, window):
    """
    Calculate a moving average at a given position in the price list.
    Returns None if there aren't enough data points yet.

    prices:   list of [datetime, close_price]
    position: current index in the list (0-based)
    window:   how many prices to average (7 or 21)
    """
    if position < window - 1:
        return None
    total = 0
    for i in range(position - window + 1, position + 1):
        total += prices[i][1]
    return total / window


def backtest(coin_name, filename, starting_capital):
    """
    Run the MA7/MA21 crossover strategy on historical data.

    Rules:
    - Start with cash, no position
    - When MA7 crosses ABOVE MA21 → BUY (spend all cash)
    - When MA7 crosses BELOW MA21 → SELL (sell everything)
    - At the end, sell any remaining position to count final value
    """

    prices = load_prices(filename)
    total_candles = len(prices)

    # State
    cash = starting_capital
    coins_held = 0.0
    position = "out"        # "out" = holding cash, "in" = holding coin

    # Tracking
    trades = []             # list of trade records
    buy_price = 0.0
    prev_signal = None      # track previous signal to detect crossovers

    print(f"\n{'='*60}")
    print(f"  BACKTEST: {coin_name} — MA7/MA21 Crossover (Hourly)")
    print(f"{'='*60}")
    print(f"  Data:     {total_candles} hourly candles")
    print(f"  Period:   {prices[0][0]}  →  {prices[-1][0]}")
    print(f"  Capital:  EUR {starting_capital:,.2f}")
    print(f"  Fee:      {FEE_PCT}% per trade (Kraken taker)")
    print(f"{'='*60}")

    # Walk through each candle
    for i in range(total_candles):
        ma7 = calculate_ma(prices, i, 7)
        ma21 = calculate_ma(prices, i, 21)

        # Need both MAs to generate a signal
        if ma7 is None or ma21 is None:
            continue

        # Determine current signal
        if ma7 > ma21:
            signal = "BUY"
        elif ma7 < ma21:
            signal = "SELL"
        else:
            signal = "HOLD"

        current_price = prices[i][1]
        current_time = prices[i][0]

        # Detect CROSSOVER — signal changed from previous reading
        if prev_signal is not None and signal != prev_signal:

            if signal == "BUY" and position == "out":
                # Buy: spend all cash, minus the fee
                fee = cash * (FEE_PCT / 100)
                cash_after_fee = cash - fee
                coins_held = cash_after_fee / current_price
                buy_price = current_price
                cash = 0.0
                position = "in"
                trades.append({
                    "type": "BUY",
                    "time": current_time,
                    "price": current_price,
                    "coins": coins_held,
                    "fee": fee,
                })

            elif signal == "SELL" and position == "in":
                # Sell: convert all coins to cash, minus the fee
                gross = coins_held * current_price
                fee = gross * (FEE_PCT / 100)
                cash = gross - fee
                profit_pct = (current_price - buy_price) / buy_price * 100
                trades.append({
                    "type": "SELL",
                    "time": current_time,
                    "price": current_price,
                    "cash": cash,
                    "profit_pct": profit_pct,
                    "fee": fee,
                })
                coins_held = 0.0
                position = "out"

        prev_signal = signal

    # End of data: if still holding, sell at last price to calculate final value
    last_price = prices[-1][1]
    if position == "in":
        gross = coins_held * last_price
        fee = gross * (FEE_PCT / 100)
        cash = gross - fee
        profit_pct = (last_price - buy_price) / buy_price * 100
        trades.append({
            "type": "SELL (end)",
            "time": prices[-1][0],
            "price": last_price,
            "cash": cash,
            "profit_pct": profit_pct,
            "fee": fee,
        })
        coins_held = 0.0
        position = "out"

    # === RESULTS ===

    final_value = cash
    total_return = (final_value - starting_capital) / starting_capital * 100

    # Buy & hold comparison: what if you just bought at the start and held?
    # Fair comparison: buy & hold also pays fees (1 buy + 1 sell)
    first_price = prices[0][1]
    bh_buy_fee = starting_capital * (FEE_PCT / 100)
    bh_coins = (starting_capital - bh_buy_fee) / first_price
    bh_gross = bh_coins * last_price
    bh_sell_fee = bh_gross * (FEE_PCT / 100)
    buy_hold_value = bh_gross - bh_sell_fee
    buy_hold_return = (buy_hold_value - starting_capital) / starting_capital * 100

    # Trade statistics
    total_fees = sum(t.get("fee", 0) for t in trades)
    sells = [t for t in trades if "SELL" in t["type"]]
    winners = [t for t in sells if t["profit_pct"] > 0]
    losers = [t for t in sells if t["profit_pct"] <= 0]

    print(f"\n  TRADES ({len(trades)} total):")
    print(f"  {'Type':<12} {'Time':<22} {'Price':>12} {'Result':>10}")
    print(f"  {'-'*56}")
    for t in trades:
        if "BUY" == t["type"]:
            print(f"  {'BUY':<12} {t['time']:<22} EUR {t['price']:>9,.2f}")
        else:
            print(f"  {t['type']:<12} {t['time']:<22} EUR {t['price']:>9,.2f} {t['profit_pct']:>+8.2f}%")

    print(f"\n  RESULTS:")
    print(f"  Starting capital:    EUR {starting_capital:>10,.2f}")
    print(f"  Final value:         EUR {final_value:>10,.2f}")
    print(f"  Total fees paid:     EUR {total_fees:>10,.2f}")
    print(f"  Strategy return:     {total_return:>+10.2f}%")
    print(f"  Buy & hold return:   {buy_hold_return:>+10.2f}%")
    print(f"  Strategy vs hold:    {total_return - buy_hold_return:>+10.2f}%")
    print()
    print(f"  Total trades:        {len(sells)} round trips")
    print(f"  Winners:             {len(winners)}")
    print(f"  Losers:              {len(losers)}")
    if sells:
        best = max(t["profit_pct"] for t in sells)
        worst = min(t["profit_pct"] for t in sells)
        print(f"  Best trade:          {best:+.2f}%")
        print(f"  Worst trade:         {worst:+.2f}%")

    print()
    return total_return, buy_hold_return


# === RUN BACKTESTS ===

STARTING_CAPITAL = 300.00  # Your trading lab budget

coins = [
    ["BTC", "history_BTC_60m.csv"],
    ["ETH", "history_ETH_60m.csv"],
    ["SOL", "history_SOL_60m.csv"],
]

print("=== Financial Bonsai — Backtester ===")
print(f"Strategy: MA7/MA21 Crossover on hourly candles")
print(f"Starting capital: EUR {STARTING_CAPITAL:,.2f} per coin")
print(f"Trading fee: {FEE_PCT}% per trade (Kraken taker rate)")

results = []
for name, filename in coins:
    strat, hold = backtest(name, filename, STARTING_CAPITAL)
    results.append([name, strat, hold])

# Final summary
print(f"\n{'='*60}")
print(f"  SUMMARY — All Coins")
print(f"{'='*60}")
print(f"  {'Coin':<6} {'Strategy':>12} {'Buy & Hold':>12} {'Difference':>12}")
print(f"  {'-'*42}")
for name, strat, hold in results:
    print(f"  {name:<6} {strat:>+11.2f}% {hold:>+11.2f}% {strat - hold:>+11.2f}%")
print()
