"""
Financial Bonsai — Multi-Strategy Backtester
Tests different MA window combinations across three timeframes.

Answers the question: is the MA *window size* the real variable,
not the timeframe? Does a golden cross (MA50/MA200) produce fewer
trades and better results than our original MA7/MA21?

Usage: python3 backtest.py
Requires: history files generated by download_history.py
"""

import csv
import os

# Kraken taker fee: 0.40% per trade (lowest volume tier, $0-$10k)
# This applies to EACH trade — both the buy and the sell
FEE_PCT = 0.40


def load_prices(filename):
    """Read a history CSV and return a list of [datetime, close_price] pairs."""
    prices = []
    with open(filename, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            prices.append([row["datetime"], float(row["close"])])
    return prices


def calculate_ma(prices, position, window):
    """
    Calculate a moving average at a given position in the price list.
    Returns None if there aren't enough data points yet.

    prices:   list of [datetime, close_price]
    position: current index in the list (0-based)
    window:   how many prices to average (7, 21, 50, 200, etc.)
    """
    if position < window - 1:
        return None
    total = 0
    for i in range(position - window + 1, position + 1):
        total += prices[i][1]
    return total / window


def backtest(coin_name, filename, starting_capital, timeframe_label, ma_fast, ma_slow):
    """
    Run an MA crossover strategy on historical data.

    ma_fast: window size for the fast (short-term) moving average
    ma_slow: window size for the slow (long-term) moving average

    Rules:
    - Start with cash, no position
    - When fast MA crosses ABOVE slow MA → BUY (spend all cash)
    - When fast MA crosses BELOW slow MA → SELL (sell everything)
    - At the end, sell any remaining position to count final value
    """

    prices = load_prices(filename)
    total_candles = len(prices)

    # State
    cash = starting_capital
    coins_held = 0.0
    position = "out"        # "out" = holding cash, "in" = holding coin

    # Tracking
    trades = []             # list of trade records
    buy_price = 0.0
    prev_signal = None      # track previous signal to detect crossovers

    strategy_name = f"MA{ma_fast}/MA{ma_slow}"

    print(f"\n{'='*60}")
    print(f"  BACKTEST: {coin_name} — {strategy_name} ({timeframe_label})")
    print(f"{'='*60}")
    print(f"  Data:     {total_candles} candles ({timeframe_label})")
    print(f"  Period:   {prices[0][0]}  →  {prices[-1][0]}")
    print(f"  Capital:  EUR {starting_capital:,.2f}")
    print(f"  Fee:      {FEE_PCT}% per trade (Kraken taker)")
    print(f"  Warm-up:  {ma_slow} candles before first signal possible")
    print(f"{'='*60}")

    # Walk through each candle
    for i in range(total_candles):
        fast_ma = calculate_ma(prices, i, ma_fast)
        slow_ma = calculate_ma(prices, i, ma_slow)

        # Need both MAs to generate a signal
        if fast_ma is None or slow_ma is None:
            continue

        # Determine current signal
        if fast_ma > slow_ma:
            signal = "BUY"
        elif fast_ma < slow_ma:
            signal = "SELL"
        else:
            signal = "HOLD"

        current_price = prices[i][1]
        current_time = prices[i][0]

        # Detect CROSSOVER — signal changed from previous reading
        if prev_signal is not None and signal != prev_signal:

            if signal == "BUY" and position == "out":
                # Buy: spend all cash, minus the fee
                fee = cash * (FEE_PCT / 100)
                cash_after_fee = cash - fee
                coins_held = cash_after_fee / current_price
                buy_price = current_price
                cash = 0.0
                position = "in"
                trades.append({
                    "type": "BUY",
                    "time": current_time,
                    "price": current_price,
                    "coins": coins_held,
                    "fee": fee,
                })

            elif signal == "SELL" and position == "in":
                # Sell: convert all coins to cash, minus the fee
                gross = coins_held * current_price
                fee = gross * (FEE_PCT / 100)
                cash = gross - fee
                profit_pct = (current_price - buy_price) / buy_price * 100
                trades.append({
                    "type": "SELL",
                    "time": current_time,
                    "price": current_price,
                    "cash": cash,
                    "profit_pct": profit_pct,
                    "fee": fee,
                })
                coins_held = 0.0
                position = "out"

        prev_signal = signal

    # End of data: if still holding, sell at last price to calculate final value
    last_price = prices[-1][1]
    if position == "in":
        gross = coins_held * last_price
        fee = gross * (FEE_PCT / 100)
        cash = gross - fee
        profit_pct = (last_price - buy_price) / buy_price * 100
        trades.append({
            "type": "SELL (end)",
            "time": prices[-1][0],
            "price": last_price,
            "cash": cash,
            "profit_pct": profit_pct,
            "fee": fee,
        })
        coins_held = 0.0
        position = "out"

    # === RESULTS ===

    final_value = cash
    total_return = (final_value - starting_capital) / starting_capital * 100

    # Buy & hold comparison: what if you just bought at the start and held?
    # Fair comparison: buy & hold also pays fees (1 buy + 1 sell)
    first_price = prices[0][1]
    bh_buy_fee = starting_capital * (FEE_PCT / 100)
    bh_coins = (starting_capital - bh_buy_fee) / first_price
    bh_gross = bh_coins * last_price
    bh_sell_fee = bh_gross * (FEE_PCT / 100)
    buy_hold_value = bh_gross - bh_sell_fee
    buy_hold_return = (buy_hold_value - starting_capital) / starting_capital * 100

    # Trade statistics
    total_fees = sum(t.get("fee", 0) for t in trades)
    sells = [t for t in trades if "SELL" in t["type"]]
    winners = [t for t in sells if t["profit_pct"] > 0]
    losers = [t for t in sells if t["profit_pct"] <= 0]

    print(f"\n  TRADES ({len(trades)} total):")
    print(f"  {'Type':<12} {'Time':<22} {'Price':>12} {'Result':>10}")
    print(f"  {'-'*56}")
    for t in trades:
        if "BUY" == t["type"]:
            print(f"  {'BUY':<12} {t['time']:<22} EUR {t['price']:>9,.2f}")
        else:
            print(f"  {t['type']:<12} {t['time']:<22} EUR {t['price']:>9,.2f} {t['profit_pct']:>+8.2f}%")

    print(f"\n  RESULTS:")
    print(f"  Starting capital:    EUR {starting_capital:>10,.2f}")
    print(f"  Final value:         EUR {final_value:>10,.2f}")
    print(f"  Total fees paid:     EUR {total_fees:>10,.2f}")
    print(f"  Strategy return:     {total_return:>+10.2f}%")
    print(f"  Buy & hold return:   {buy_hold_return:>+10.2f}%")
    print(f"  Strategy vs hold:    {total_return - buy_hold_return:>+10.2f}%")
    print()
    print(f"  Total trades:        {len(sells)} round trips")
    print(f"  Winners:             {len(winners)}")
    print(f"  Losers:              {len(losers)}")
    if sells:
        best = max(t["profit_pct"] for t in sells)
        worst = min(t["profit_pct"] for t in sells)
        print(f"  Best trade:          {best:+.2f}%")
        print(f"  Worst trade:         {worst:+.2f}%")

    print()

    # Return data for the comparison table
    return {
        "coin": coin_name,
        "timeframe": timeframe_label,
        "strategy": strategy_name,
        "candles": total_candles,
        "round_trips": len(sells),
        "total_fees": total_fees,
        "strategy_return": total_return,
        "buy_hold_return": buy_hold_return,
        "difference": total_return - buy_hold_return,
    }


# === CONFIGURATION ===

STARTING_CAPITAL = 300.00  # Your trading lab budget

COINS = [
    "BTC",
    "ETH",
    "SOL",
]

# [interval_minutes, human_label]
TIMEFRAMES = [
    [60, "hourly"],
    [240, "4-hour"],
    [1440, "daily"],
]

# [fast_window, slow_window, description]
MA_STRATEGIES = [
    [7, 21, "Original seatbelt"],
    [20, 50, "Medium filter"],
    [50, 200, "Golden cross"],
]

print("=== Financial Bonsai — Multi-Strategy Backtester ===")
print(f"Strategies: {', '.join(f'MA{f}/MA{s}' for f, s, _ in MA_STRATEGIES)}")
print(f"Timeframes: {', '.join(t[1] for t in TIMEFRAMES)}")
print(f"Starting capital: EUR {STARTING_CAPITAL:,.2f} per coin")
print(f"Trading fee: {FEE_PCT}% per trade (Kraken taker rate)")

all_results = []

for coin in COINS:
    for interval, label in TIMEFRAMES:
        for ma_fast, ma_slow, description in MA_STRATEGIES:
            filename = f"history_{coin}_{interval}m.csv"

            # Check that the data file exists
            if not os.path.exists(filename):
                print(f"\n  ⚠ Skipping {coin} ({label}): {filename} not found.")
                print(f"    Run download_history.py first to generate data files.")
                continue

            result = backtest(coin, filename, STARTING_CAPITAL, label, ma_fast, ma_slow)
            all_results.append(result)

# === COMPARISON TABLE ===

print(f"\n{'='*90}")
print(f"  GRAND COMPARISON — Window Size vs Timeframe vs Fees")
print(f"{'='*90}")
print(f"  {'Coin':<5} {'Time':<8} {'Strategy':<12} {'Trades':>7} {'Fees':>10} {'Return':>9} {'B&H':>9} {'Diff':>9}")
print(f"  {'-'*69}")

current_coin = None
current_tf = None
for r in all_results:
    # Add spacing between coins
    if current_coin is not None and r["coin"] != current_coin:
        print(f"  {'-'*69}")
    # Add blank line between timeframes within same coin
    elif current_tf is not None and r["timeframe"] != current_tf:
        print()

    current_coin = r["coin"]
    current_tf = r["timeframe"]

    print(f"  {r['coin']:<5} {r['timeframe']:<8} {r['strategy']:<12} {r['round_trips']:>7} "
          f"EUR {r['total_fees']:>6,.2f} {r['strategy_return']:>+8.2f}% {r['buy_hold_return']:>+8.2f}% {r['difference']:>+8.2f}%")

# === KEY FINDINGS ===

print(f"\n{'='*90}")
print(f"  KEY FINDINGS")
print(f"{'='*90}")

# Find best and worst results
best = max(all_results, key=lambda r: r["strategy_return"])
least_trades = min(all_results, key=lambda r: r["round_trips"])
least_fees = min(all_results, key=lambda r: r["total_fees"])
best_vs_hold = max(all_results, key=lambda r: r["difference"])

print(f"  Best absolute return:   {best['coin']} {best['timeframe']} {best['strategy']} → {best['strategy_return']:+.2f}%")
print(f"  Best vs buy & hold:     {best_vs_hold['coin']} {best_vs_hold['timeframe']} {best_vs_hold['strategy']} → {best_vs_hold['difference']:+.2f}%")
print(f"  Fewest trades:          {least_trades['coin']} {least_trades['timeframe']} {least_trades['strategy']} → {least_trades['round_trips']} round trips")
print(f"  Lowest fees:            {least_fees['coin']} {least_fees['timeframe']} {least_fees['strategy']} → EUR {least_fees['total_fees']:,.2f}")
print()
